package com.devapplab.model

import kotlinx.serialization.Serializable

@Serializable
enum class ErrorCode {
    GENERAL_ERROR,
    TOO_MANY_REQUESTS,
    AUTH_USER_BLOCKED,
    AUTH_USER_SUSPENDED,
    AUTH_NEED_LOGIN,
    AUTH_EMAIL_NOT_VERIFIED,
    ACCESS_DENIED,
    ALREADY_EXISTS,
    NOT_FOUND,
    AUTH_USER_NOT_VERIFIED,
    AUTH_INVALID_PASSWORD_RESET,
    AUTH_EMAIL_DOMAIN_NOT_ALLOWED,
    MFA_GENERATION_LOCKED,
    MATCH_OVERLAP,
    MATCH_FULL,
    MATCH_NOT_SCHEDULED,
    MATCH_TEAM_FULL,
    MATCH_JOIN_TOO_EARLY,
    MATCH_PRICE_BELOW_FIELD_COST,
    MATCH_ALREADY_COMPLETED,
    MATCH_COMPLETE_ENDPOINT_REQUIRED,
    MATCH_INVALID_REBALANCE_PLAYERS,
    MATCH_REBALANCE_TEAM_LIMIT,
    INVALID_BEST_PLAYER,
    PAYMENT_FAILED
}
